![sslogo](https://github.com/stratascratch/stratascratch.github.io/raw/master/assets/sslogo.jpg)

# A Few More Numpy and Pandas Exercises 

To edit this notebook:
- Save the notebook by selecting `Download .ipynb` from the `File` tab
- Go to https://colab.research.google.com/ and upload the notebook from the `File` tab
- Alternatively, you can import the notebook to your Google Drive and select `Open with` when you right-click. Select `Colaboratory` or `+ Connect more apps` to install Colaboratory first

#### Import Numpy and Pandas

In [0]:
import numpy as np
import pandas as pd

#### Create an array of 64 values starting with 10 and ending with 15 and assign it to x

In [2]:
x=np.linspace(10, 15, 64)
x

array([10.        , 10.07936508, 10.15873016, 10.23809524, 10.31746032,
       10.3968254 , 10.47619048, 10.55555556, 10.63492063, 10.71428571,
       10.79365079, 10.87301587, 10.95238095, 11.03174603, 11.11111111,
       11.19047619, 11.26984127, 11.34920635, 11.42857143, 11.50793651,
       11.58730159, 11.66666667, 11.74603175, 11.82539683, 11.9047619 ,
       11.98412698, 12.06349206, 12.14285714, 12.22222222, 12.3015873 ,
       12.38095238, 12.46031746, 12.53968254, 12.61904762, 12.6984127 ,
       12.77777778, 12.85714286, 12.93650794, 13.01587302, 13.0952381 ,
       13.17460317, 13.25396825, 13.33333333, 13.41269841, 13.49206349,
       13.57142857, 13.65079365, 13.73015873, 13.80952381, 13.88888889,
       13.96825397, 14.04761905, 14.12698413, 14.20634921, 14.28571429,
       14.36507937, 14.44444444, 14.52380952, 14.6031746 , 14.68253968,
       14.76190476, 14.84126984, 14.92063492, 15.        ])

#### Create a random shuffled array of values that include the range of values from 0 to 63 and assign to a variable called indices

In [6]:
indices=np.random.randint(0, 64, 63)
indices

array([ 8,  0, 56, 53, 42,  8, 24, 30, 63, 35, 57, 33, 62, 16, 18, 13, 17,
       20,  7, 32, 53, 23, 49, 50, 20, 24, 40, 46, 13, 34, 22, 33,  8, 27,
        9, 27, 52, 57, 47, 11, 55, 62, 10, 53, 24, 46, 31, 20, 40, 55, 40,
       46, 60, 24, 41, 35, 56, 40, 11,  4, 62, 14, 59])

#### Shuffle the data in x using the values in indices

#### Reshape x into a 3-Dimensional Array

In [7]:
len(x)

64

In [9]:
x.reshape(8,4,2)

array([[[10.        , 10.07936508],
        [10.15873016, 10.23809524],
        [10.31746032, 10.3968254 ],
        [10.47619048, 10.55555556]],

       [[10.63492063, 10.71428571],
        [10.79365079, 10.87301587],
        [10.95238095, 11.03174603],
        [11.11111111, 11.19047619]],

       [[11.26984127, 11.34920635],
        [11.42857143, 11.50793651],
        [11.58730159, 11.66666667],
        [11.74603175, 11.82539683]],

       [[11.9047619 , 11.98412698],
        [12.06349206, 12.14285714],
        [12.22222222, 12.3015873 ],
        [12.38095238, 12.46031746]],

       [[12.53968254, 12.61904762],
        [12.6984127 , 12.77777778],
        [12.85714286, 12.93650794],
        [13.01587302, 13.0952381 ]],

       [[13.17460317, 13.25396825],
        [13.33333333, 13.41269841],
        [13.49206349, 13.57142857],
        [13.65079365, 13.73015873]],

       [[13.80952381, 13.88888889],
        [13.96825397, 14.04761905],
        [14.12698413, 14.20634921],
        [14.2857

#### Pull the Titanic dataset from the Strata Scratch platform

In [10]:
#code is copy and pasted from the Connect to Strata Scratch with Python.ipynb notebook

!pip install psycopg2
import psycopg2 as ps

/usr/local/lib/python3.6/dist-packages/psycopg2/__init__.py:144: UserWarning: The psycopg2 wheel package will be renamed from release 2.8; in order to keep installing from binary please use "pip install psycopg2-binary" instead. For details see: <http://initd.org/psycopg/docs/install.html#binary-install-from-pypi>.
  """)


In [11]:
host_name = 'db-strata.stratascratch.com'
dbname = 'db_strata'
port = '5432'
user_name = 'ankit082006' #enter username
pwd = 'ofkMQPktC' #enter your database password found in the profile tab in Strata Scratch

try:
    conn = ps.connect(host=host_name,database=dbname,user=user_name,password=pwd,port=port)
except ps.OperationalError as e:
    raise e
else:
    print('Connected!')

Connected!


In [0]:
#Write SQL below to pull datasets 
cur = conn.cursor()
cur.execute(""" 
            SELECT *  FROM titanic; 
            """)
data = cur.fetchall()
colnames = [desc[0] for desc in cur.description] 
conn.commit()

#create the pandas dataframe
data = pd.DataFrame(data)
data.columns = colnames

#close the connection
cur.close()

In [13]:
data

passengerid  survived  pclass  ...     fare cabin embarked
0              1         0       3  ...   7.2500  None        S
1              2         1       1  ...  71.2833   C85        C
2              3         1       3  ...   7.9250  None        S
3              4         1       1  ...  53.1000  C123        S
4              5         0       3  ...   8.0500  None        S
..           ...       ...     ...  ...      ...   ...      ...
886          887         0       2  ...  13.0000  None        S
887          888         1       1  ...  30.0000   B42        S
888          889         0       3  ...  23.4500  None        S
889          890         1       1  ...  30.0000  C148        C
890          891         0       3  ...   7.7500  None        Q

[891 rows x 12 columns]

#### Investigate the DataFrame (e.g., Check first 5 rows of data, data types and review any summary statistics)

In [14]:
data.head()

passengerid  survived  pclass  ...     fare cabin embarked
0            1         0       3  ...   7.2500  None        S
1            2         1       1  ...  71.2833   C85        C
2            3         1       3  ...   7.9250  None        S
3            4         1       1  ...  53.1000  C123        S
4            5         0       3  ...   8.0500  None        S

[5 rows x 12 columns]

In [15]:
data.dtypes

passengerid      int64
survived         int64
pclass           int64
name            object
sex             object
age             object
sibsp            int64
parch            int64
ticket          object
fare           float64
cabin           object
embarked        object
dtype: object

In [16]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 891 entries, 0 to 890
Data columns (total 12 columns):
passengerid    891 non-null int64
survived       891 non-null int64
pclass         891 non-null int64
name           891 non-null object
sex            891 non-null object
age            714 non-null object
sibsp          891 non-null int64
parch          891 non-null int64
ticket         891 non-null object
fare           891 non-null float64
cabin          204 non-null object
embarked       889 non-null object
dtypes: float64(1), int64(5), object(6)
memory usage: 83.7+ KB


In [17]:
data.describe()

passengerid    survived      pclass       sibsp       parch        fare
count   891.000000  891.000000  891.000000  891.000000  891.000000  891.000000
mean    446.000000    0.383838    2.308642    0.523008    0.381594   32.204208
std     257.353842    0.486592    0.836071    1.102743    0.806057   49.693429
min       1.000000    0.000000    1.000000    0.000000    0.000000    0.000000
25%     223.500000    0.000000    2.000000    0.000000    0.000000    7.910400
50%     446.000000    0.000000    3.000000    0.000000    0.000000   14.454200
75%     668.500000    1.000000    3.000000    1.000000    0.000000   31.000000
max     891.000000    1.000000    3.000000    8.000000    6.000000  512.329200

#### What was the survival rate for men over the age of 50 in first class?

In [18]:
data[(data['sex']=='male') & (data['survived']==1)]

passengerid  survived  pclass  ...     fare cabin embarked
17            18         1       2  ...  13.0000  None        S
21            22         1       2  ...  13.0000   D56        S
23            24         1       1  ...  35.5000    A6        S
36            37         1       3  ...   7.2292  None        C
55            56         1       1  ...  35.5000   C52        S
..           ...       ...     ...  ...      ...   ...      ...
838          839         1       3  ...  56.4958  None        S
839          840         1       1  ...  29.7000   C47        C
857          858         1       1  ...  26.5500   E17        S
869          870         1       3  ...  11.1333  None        S
889          890         1       1  ...  30.0000  C148        C

[109 rows x 12 columns]

In [22]:
len(data[(data['sex']=='male') & (data['survived']==1)  & (data['age']>50) & (data['pclass']==1)])

5

In [24]:
len(data[(data['sex']=='male') & (data['survived']==1)])

109

In [26]:
((len(data[(data['sex']=='male') & (data['survived']==1)  & (data['age']>50) & (data['pclass']==1)]))
/(len(data[(data['sex']=='male') & (data['survived']==1)])))*100

4.587155963302752

#### Using groupby, count the number of passengers by Sex, Pclass and Survived (Hint: use three columns for group by)

In [28]:
data.groupby(['sex','pclass','survived'])['passengerid'].count()

sex     pclass  survived
female  1       0             3
                1            91
        2       0             6
                1            70
        3       0            72
                1            72
male    1       0            77
                1            45
        2       0            91
                1            17
        3       0           300
                1            47
Name: passengerid, dtype: int64

#### Create a pipe delimited csv with only the names and ages of the 10 oldest surivors

In [33]:
tmp=data[["name","age"]]
tmp.sort_values(by='age', ascending=False, inplace=True)
tmp.iloc[:10].to_csv('data_age.csv')

/usr/local/lib/python3.6/dist-packages/ipykernel_launcher.py:2: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  
